// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "tileSet-main":return img`
3ffdff43ffdff43ffdff43fffff43fffff43ffdff4
.ffdff4.ffdff4.ffdff4.fffff4.fdddd4.ffdff4
.ddddd4.ffddd4.ffdff4.fffff4.fdddd4.ddddd4
.fffff4.fffff4.ffdff4.fffff4.fdddd4.ffdff4
.fffff3.fffff3.ffdff3.fffff3.fdddd3.ffdff1
3ddddd43fdddd43fdddd43fdddd43fdddd43fffff4
.ddddd4.fdddd4.fdddd4.ddddd4.fdddd4.fdddd4
.ddddd4.ddddd4.fdddd4.ddddd4.ddddd4.ddddd4
.ddddd4.fdddd4.fdddd4.ddddd4.fdddd4.fdddd4
.ddddd3.fdddd3.fdddd3.ddddd3.fffff3.fdddd2
..........................................
..........................................
..........................................
..........................................
..........................................
..........................................
..........................................
..........................................
..........................................
..........................................
..........................................
..........................................
..........................................
..........................................
..........................................
..........................................
..........................................
..........................................
..........................................
..........................................
..........................................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.

// Auto-generated code. Do not edit.
namespace myTiles {

}
// Auto-generated code. Do not edit.
